//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Better.Benefits.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.Policies = new HashSet<Policy>();
            this.Members = new HashSet<Policy_Member>();
            this.Identities = new HashSet<Person_Identity>();
            this.Row = new Row();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid PersonId { get; set; }
        public string IsAgent { get; set; }
        public string IsClient { get; set; }
        public string IsStaff { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
    
        public Row Row { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Policy> Policies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Policy_Member> Members { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person_Identity> Identities { get; set; }
    }
}
