//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Better.Benefits.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person_Identity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person_Identity()
        {
            this.Name = new PersonName();
            this.Row = new Row();
        }
    
        public byte IdentityTypeNo { get; set; }
        public string CountryCode { get; set; }
        public string Number { get; set; }
        public System.Guid Id { get; set; }
        public byte[] Image { get; set; }
        public System.Guid PersonId { get; set; }
    
        public PersonName Name { get; set; }
        public Row Row { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Person Person { get; set; }
        public virtual Person_IdentityType IdentityType { get; set; }
    }
}
