//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Better.Benefits.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Policy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Policy()
        {
            this.Members = new HashSet<Policy_Member>();
            this.Receipts = new HashSet<Policy_Receipt>();
            this.Row = new Row();
        }
    
        public string Code { get; set; }
        public byte TypeNo { get; set; }
        public byte StatusNo { get; set; }
        public System.Guid OwnerPersonId { get; set; }
        public System.Guid Id { get; set; }
        public System.Guid PolicyId { get; set; }
    
        public Row Row { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Policy_Member> Members { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Policy_Receipt> Receipts { get; set; }
        public virtual Policy_Type Type { get; set; }
        public virtual Policy_Status Status { get; set; }
        public virtual Person OwnerPerson { get; set; }
    }
}
