//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Better.Benefits.Data
{
    using System;
    
    public partial class Row
    {
        public int Version { get; set; }
        public bool Archived { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public bool DeletedParent { get; set; }
        public Nullable<System.DateTime> ArchivedOn { get; set; }
    }
}
